### ISSUE TITLE
Перевод.

### ISSUE THREAD

**Issue by ItDanieru** [Hoaper/dawncraft-russian#2]
Доброго времени суток, я перевожу актуальную сборку DawnCraft для русскоговорящего комьюнити, на данный момент полностью перевел FTB Quests, мог бы я использовать ваш перевод мода Quest Giver?

**Comment by Hoaper** [comment]
Доброго времени суток. Да, конечно. 
Но укажите в соавторстве линк на гитхаб
Можем заколабиться и сделать перевод на весь проект DawnCraft
Дайте знать в комментарии.
